### ISSUE TITLE
Error while using Factions

### ISSUE THREAD

**Issue by Nyxiu** [drtshock/Factions#1000]
FactionsUUID version (run `/f version`): [15:40:55 INFO]: You are running Factions v1.6.9.5-U0.2.0-SNAPSHOT-b27

Server software (run `/version`): PaperSpigot - 1.8.8

Server (`logs/latest.log`):
[15:32:44] [Server thread/WARN]: Unexpected exception while parsing console command "f who ciao"
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.0-SNAPSHOT-b27
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:207) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:91) ~[?:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:91) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:295) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:258) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:221) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:232) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[UltraOpFactions.jar:git-PaperSpigot-"8b18730"]
	... 8 more

Details: When I try to use a command, the command just doesn't work.

**Comment by WizzleBear** [comment]
What is "UltraOpFactions.jar" and try setting the "allowNoSlashCommand" in the conf.json file to false.

**Comment by drtshock** [comment]
Try updating to latest dev build and tell me if still an issue.
