### ISSUE TITLE
Issue with new build

### ISSUE THREAD

**Issue by Agazed** [drtshock/Factions#1011]
After updating to dev build 29, i'm getting an error when using /f who

Using PaperSpigot 1.8.8

`[16:18:12] [Server thread/INFO]: iFHRITP issued server command: /f who Aurora
[16:18:12] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.0-SNAPSHOT-b29
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [paper.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paper.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paper.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.util.MiscUtil.rankOrder(MiscUtil.java:91) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:203) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:91) ~[?:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:91) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:295) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:258) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:221) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:232) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper.jar:git-PaperSpigot-"4c7641d"]
	... 15 more`

**Comment by drtshock** [comment]
Resolving this in discord. Will update the ticket once I've had a chance to figure out the issue.

**Comment by drtshock** [comment]
Should be fixed on new dev builds.
