### ISSUE TITLE
error 2 (/f who)

### ISSUE THREAD

**Issue by SayNada** [drtshock/Factions#1013]
[23:15:25] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.0-SNAPSHOT-b29
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"bf023c7d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"bf023c7d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [patched.jar:git-TacoSpigot-"bf023c7d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
	at com.massivecraft.factions.util.MiscUtil.rankOrder(MiscUtil.java:91) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:188) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:91) ~[Factions.jar:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:91) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[Factions.jar:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[Factions.jar:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:295) ~[Factions.jar:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:258) ~[Factions.jar:?]
	at com.massivecraft.factions.P.handleCommand(P.java:221) ~[Factions.jar:?]
	at com.massivecraft.factions.P.onCommand(P.java:232) ~[Factions.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"bf023c7d"]
	... 15 more

**Comment by drtshock** [comment]
Try on build 34. Should be fixed.
