### ISSUE TITLE
F ban error - With Solution

### ISSUE THREAD

**Issue by VictorML11** [drtshock/Factions#1162]
FactionsUUID version (run `/f version`): You are running Factions v1.6.9.5-U0.2.2 - Latest Build from SpigotMC

Server software (run `/version`): CustomSpigot 1.8.8

Server (`logs/latest.log`): None

Basically there was a mistake at the code with the last Fix TL commit at **CmdBan** line 100.

I solved it changing it for this:
`target.msg(TL.COMMAND_BAN_TARGET, myFaction.getTag(target));`

Details:
`[17:27:23 INFO]: Torciv issued server command: /f ban Mr_Senes
[17:27:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[fluxJar.jar:FluxSpigot-6595c501]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[fluxJar.jar:FluxSpigot-6595c501]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:619) ~[fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [fluxJar.jar:FluxSpigot-6595c501]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [fluxJar.jar:FluxSpigot-6595c501]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [fluxJar.jar:FluxSpigot-6595c501]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.util.MissingFormatArgumentException: Format specifier '%2$s'
        at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_161]
        at java.util.Formatter.format(Unknown Source) ~[?:1.8.0_161]
        at java.lang.String.format(Unknown Source) ~[?:1.8.0_161]
        at com.massivecraft.factions.zcore.util.TextUtil.parse(TextUtil.java:24) ~[?:?]
        at com.massivecraft.factions.zcore.persist.MemoryFPlayer.msg(MemoryFPlayer.java:878) ~[?:?]
        at com.massivecraft.factions.zcore.persist.MemoryFPlayer.msg(MemoryFPlayer.java:882) ~[?:?]
        at com.massivecraft.factions.cmd.CmdBan.perform(CmdBan.java:100) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:295) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:258) ~[?:?]
        at com.massivecraft.factions.P.handleCommand(P.java:241) ~[?:?]
        at com.massivecraft.factions.P.onCommand(P.java:252) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[fluxJar.jar:FluxSpigot-6595c501]
        ... 15 more`

**Comment by dariasc** [comment]
Can we get this fix on it's own PR?

**Comment by CmdrKittens** [comment]
It is my understanding this was resolved.
