### ISSUE TITLE
Broken F who with luckperms

### ISSUE THREAD

**Issue by drtshock** [drtshock/Factions#1178]
```[04:27:11] [Server thread/INFO]: Vake issued server command: /f who J6rpa
[04:27:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.2.1-RC-1.4-RC-2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[my-jar.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[my-jar.jar:git-TacoSpigot-bf023c7d]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) ~[my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1178) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:991) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627) [my-jar.jar:git-TacoSpigot-bf023c7d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: The operation to load user data for 'a65d4ac7-3e2f-46e3-b1ef-8b70aa61b36b' was cancelled by LuckPerms. This is NOT a bug. 
The lookup request was made on the main server thread. It is not safe to execute a request to 
load username data from the database in this context. 
If you are a plugin author, please consider making your request asynchronously. 
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true 
in the LP config, but should consider the consequences (lag) before doing so.
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.lookupUser(VaultPermissionHook.java:135) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.VaultPermissionHook.userGetPrimaryGroup(VaultPermissionHook.java:241) ~[?:?]
	at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPrimaryGroup(AbstractVaultPermission.java:384) ~[?:?]
	at com.massivecraft.factions.P.getPrimaryGroup(P.java:644) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:172) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:49) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:262) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:225) ~[?:?]
	at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:93) ~[?:?]
	at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:96) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:123) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:55) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:109) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:55) ~[?:?]
	at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:127) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:288) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:251) ~[?:?]
	at com.massivecraft.factions.P.handleCommand(P.java:472) ~[?:?]
	at com.massivecraft.factions.P.onCommand(P.java:483) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[my-jar.jar:git-TacoSpigot-bf023c7d]
	... 15 more```

**Comment by ArtelGG** [comment]
How were you able to produce this? I couldn't on my test server.
```
[09:01:59 INFO]: Homework issued server command: /f create Test
[09:01:59 WARN]: [Factions v1.6.9.5-U0.2.2-b122] Resetting permissions for Faction: ???
[09:01:59 INFO]: [Factions v1.6.9.5-U0.2.2-b122] Homework created a new faction: Test
[09:02:00 INFO]: Homework issued server command: /f who
lp
[09:02:24 INFO]: [LP] Running LuckPerms v4.3.2.
[09:02:24 INFO]: [LP] Use /lp help to view available commands.
```

**Comment by Drc-DEV** [comment]
Fix this please

**Comment by drtshock** [comment]
My recommendation is to use the luckperms placeholder for user groups then since they use cached data that we would need to hook directly into the plugin to access.

**Comment by aeonlamb** [comment]
Why was this issue closed? This is a big problem on my server. People can't view who's in other factions due to this, and I'm hesitant to disable the catch in luckperms because of the warning about lag... I don't want to remove a safety check like that for my whole server just because 1 command in 1 plugin doesn't work like it should.

**Comment by drtshock** [comment]
@aeonlamb I gave instructions on how to workaround this as saving a cache of user groups in Factions doesn't seem reasonable.

Rather than using FactionUUID's placeholder {rank} to get the user's primary group, use PlaceholderAPI to get the user's primary group.

**Comment by aeonlamb** [comment]
No offense or anything, but I don't think having to install a third-party plugin just to make one command work for displaying peoples' usernames is much of a "fix"... I don't use placeholderapi on my server, it'd be annoying to have to set it up and configure it just to fix one command.

EDIT: this can be fixed by simply removing the {group} variable from the /f show tooltip, in the config.yml  file. It causes errors with the default config still, though.
