### ISSUE TITLE
Console error.

### ISSUE THREAD

**Issue by d1One** [drtshock/Factions#118]
Here is the log:
[00:35:56] [Server thread/INFO]: Dyl_Bill issued server command: /f enemy American_warior
[00:35:56] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.9
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
    at com.massivecraft.factions.scoreboards.FTeamWrapper.updatePrefixes(FTeamWrapper.java:78) ~[?:?]
    at com.massivecraft.factions.cmd.FRelationCommand.perform(FRelationCommand.java:90) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:122) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:108) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:126) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:292) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:255) ~[?:?]
    at com.massivecraft.factions.P.handleCommand(P.java:173) ~[?:?]
    at com.massivecraft.factions.P.onCommand(P.java:185) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot_1649.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 13 more

**Comment by drtshock** [comment]
You're not on the latest build. This was fixed awhile ago. Please update to 0.1.10 or newer.
