### ISSUE TITLE
Latest development build startup error

### ISSUE THREAD

**Issue by ArtelGG** [drtshock/Factions#1181]
**Server Version:** PaperSpigot 1.8.8
**Plugin Version:** 1.6.9.5-U0.2.3-b123
**Error:**
```
[05:41:30] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.2.3-b123
[05:41:30] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b123] === ENABLE START ===
[05:41:30] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.2.3-b123 (Is it up to date?)
java.lang.NoSuchFieldError: OAK_DOOR
	at com.massivecraft.factions.Conf.<clinit>(Conf.java:400) ~[?:?]
	at com.massivecraft.factions.zcore.MPlugin.preEnable(MPlugin.java:101) ~[?:?]
	at com.massivecraft.factions.P.onEnable(P.java:76) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Jar.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [Jar.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[05:41:30] [Server thread/INFO]: [Factions] Disabling Factions v1.6.9.5-U0.2.3-b123
[05:41:30] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b123] Disabled
```

**Comment by dariasc** [comment]
Will be fixed with #1180, the current version doesn't have cross material support
