### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#1190]
```
[07:44:15] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.2.3-b126
[07:44:15] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b126] === ENABLE START ===
[07:44:15] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b126] Creating default: plugins/Factions/conf.json
[07:44:15] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b126] Found Essentials. We'll delete player homes in their old Faction's when kicked.
[07:44:15] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b126] Loaded 0 players
[07:44:15] [Server thread/WARN]: [Factions v1.6.9.5-U0.2.3-b126] Resetting permissions for Faction: ???
[07:44:15] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.2.3-b126 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.massivecraft.factions.struct.Relation
    at com.massivecraft.factions.zcore.persist.MemoryFaction.resetPerms(MemoryFaction.java:421) ~[?:?]
    at com.massivecraft.factions.zcore.persist.MemoryFaction.<init>(MemoryFaction.java:473) ~[?:?]
    at com.massivecraft.factions.zcore.persist.json.JSONFaction.<init>(JSONFaction.java:15) ~[?:?]
    at com.massivecraft.factions.zcore.persist.json.JSONFactions.generateFactionObject(JSONFactions.java:239) ~[?:?]
    at com.massivecraft.factions.zcore.persist.MemoryFactions.load(MemoryFactions.java:22) ~[?:?]
    at com.massivecraft.factions.zcore.persist.json.JSONFactions.load(JSONFactions.java:71) ~[?:?]
    at com.massivecraft.factions.P.onEnable(P.java:102) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-507]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-507]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-507]
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-507]
    at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-507]
    at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-507]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-507]
    at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-507]
    at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-507]
    at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-507]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
[07:44:15] [Server thread/INFO]: [Factions] Disabling Factions v1.6.9.5-U0.2.3-b126
[07:44:15] [Server thread/INFO]: [Factions v1.6.9.5-U0.2.3-b126] Disabled
```

paper 507
factionsuuid as of https://github.com/drtshock/Factions/commit/86270227eed436f5891dcd327ab9b8e8cde94289

**Comment by CmdrKittens** [comment]
Assuming this is no longer an issue?
