### ISSUE TITLE
Certain /f commands are causing internal errors

### ISSUE THREAD

**Issue by Tribulationfu28** [drtshock/Factions#120]
When I type /f map this is what appears in the console:
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at com.massivecraft.factions.P.onCommand(P.java:185) ~[?:?]
at com.massivecraft.factions.P.handleCommand(P.java:173) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:254) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:291) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:126) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:108) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:122) ~[?:?]
at com.massivecraft.factions.cmd.CmdMap.perform(CmdMap.java:54) ~[?:?]
at com.massivecraft.factions.cmd.CmdMap.showMap(CmdMap.java:59) ~[?:?]
at com.massivecraft.factions.zcore.persist.MemoryBoard.getMap(MemoryBoard.java:191) ~[?:?]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043) [spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]
tServer.dispatchCommand(CraftServer.java:767) ~[spigot21.jar:git-Spigot-1.7.9-R0.2-205-g48578ee]

**Comment by drtshock** [comment]
Please paste the full stack trace in a https://gist.github.com
