### ISSUE TITLE
/f stuck causes exception in 1.14.3

### ISSUE THREAD

**Issue by animeavi** [drtshock/Factions#1215]
### FactionsUUID Version
`You are running Factions v1.6.9.5-U0.4.0` (latest git at the time of writing)

### Server Version
` Paper version git-Paper-a51823a7 (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)`

### Logs
```
[09:17:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.4.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Paper-a51823a7]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[spigot.jar:git-Paper-a51823a7]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1831) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1639) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$2957.00000000340AC5B0.run(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[spigot.jar:git-Paper-a51823a7]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[spigot.jar:git-Paper-a51823a7]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.UnsupportedOperationException: Use BukkitRunnable#runTaskLater(Plugin, long)
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:599) ~[spigot.jar:git-Paper-a51823a7]
	at com.massivecraft.factions.cmd.CmdStuck.perform(CmdStuck.java:45) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:70) ~[?:?]
	at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:56) ~[?:?]
	at com.massivecraft.factions.cmd.FCmdRoot.onCommand(FCmdRoot.java:219) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot.jar:git-Paper-a51823a7]
	... 18 more
```

### Details
Whenever I try to use `/f stuck` in 1.14.3 I get an exception.

**Comment by drtshock** [comment]
Another API change. Will need to update, thanks.

**Comment by CmdrKittens** [comment]
https://github.com/drtshock/Factions/commit/5b76db519ddab52da01a132b92e2cab1a4d5f0d2

Should be resolved as of this commit.
