### ISSUE TITLE
NullPointerException in Dynmap support

### ISSUE THREAD

**Issue by eirikh1996** [drtshock/Factions#1396]
### Debug info
*Run `/f debug mini` and paste or screenshot all four lines here.* 

> f debug mini
[10:57:52 INFO]: Paper version: git-Paper-88 (MC: 1.16.1)
[10:57:52 INFO]: Server ID: 41204d69-6e65-4fac-afac-00143ade68b1
[10:57:52 INFO]: Plugin version: 1.6.9.5-U0.5.15-b233
[10:57:52 INFO]: Java version: 1.8.0_201

### Logs
*Give use your logs by going to `logs/latest.log`.*
https://pastebin.com/RzD62Mgr

### Details
*Please explain the problem.*
The problem is that the task that updates faction areas on dynmap is generating a NullPointerException:
```
[10:53:02 WARN]: [Factions] Task #46 for Factions v1.6.9.5-U0.5.15-b233 generated an exception
java.lang.NullPointerException: null
        at org.dynmap.bukkit.DynmapPlugin.getMarkerAPI(DynmapPlugin.java:1011) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.updateCore(EngineDynmap.java:128) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.lambda$init$0(EngineDynmap.java:100) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-88]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-88]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-88]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

Plugins that I have:
> pl
[11:01:26 INFO]: Plugins (19): Cannons, Citizens, DtlPlayershops, dynmap*, Essentials, Factions, LuckPerms, Movecraft, Multiverse-Core, Periscopes, PermissionsEx*, spark, StructureBoxes, Towny, Vault, void-generator, WorldBorder, WorldEdit, WorldGuard

**Comment by CmdrKittens** [comment]
Dynmap is not loaded, but did not appropriately bail out of starting up. Dynmap issue, though better fixed through running a supported dynmap jar.
