### ISSUE TITLE
/f vault with no vault number causes stacktrace

### ISSUE THREAD

**Issue by timriker** [drtshock/Factions#1444]
### Debug infg
*Run `/f ticketinfo` and paste the URL here.*
https://info.factions.support/b6a5170002894e48803cec3571a76fc9

### Logs
*Give use your logs by going to `logs/latest.log`.*
[23:32:15] [Server thread/INFO]: Nuggethefirst issued server command: /f vault
[23:32:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.6.8-b279
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2108) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2089) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-240]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'com.drtshock.playervaults.config.file.Translation com.drtshock.playervaults.PlayerVaults.getTL()'
        at com.massivecraft.factions.cmd.CmdVault.perform(CmdVault.java:64) ~[Factions-279.jar:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:76) ~[Factions-279.jar:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:62) ~[Factions-279.jar:?]
        at com.massivecraft.factions.cmd.FCmdRoot.onCommand(FCmdRoot.java:275) ~[Factions-279.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more

### Details
*Please explain the problem.*
Players issue /f vault with no vault number, causes stacktrace.

**Comment by mbax** [comment]
Please update both plugins and report back.

**Comment by timriker** [comment]
This is a personal server for my kids. I've not registered either one. I'm running the latest Jenkins build I am aware of.
Updated Factions-uuid to #281 and testing that....
Same stacktrace.
[20:50:51 INFO]: TimRiker issued server command: /f vault
[20:50:51 WARN]: [Factions] Loaded class com.drtshock.playervaults.PlayerVaults from PlayerVaults v4.1.3 which is not a depend or softdepend of this plugin.
[20:50:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.6.9-b281
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2108) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2089) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1401) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1378) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1371) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1349) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.18.2.jar:git-Paper-240]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-240]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'com.drtshock.playervaults.config.file.Translation com.drtshock.playervaults.PlayerVaults.getTL()'
        at com.massivecraft.factions.cmd.CmdVault.perform(CmdVault.java:64) ~[Factions-281.jar:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:76) ~[Factions-281.jar:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:62) ~[Factions-281.jar:?]
        at com.massivecraft.factions.cmd.FCmdRoot.onCommand(FCmdRoot.java:275) ~[Factions-281.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more

**Comment by mbax** [comment]
Output of `/version playervaults` ?

**Comment by timriker** [comment]
> version playervaults
[04:56:20 INFO]: PlayerVaults version 4.1.3
[04:56:20 INFO]: Website: https://www.spigotmc.org/resources/51204/
[04:56:20 INFO]: Authors: drtshock and kashike

Ah hah! Upgraded to PlayerVaultsX 5.2.5 from here:

https://ci.ender.zone/job/PlayerVaultsX/28/

> version playervaults
[05:05:17 INFO]: PlayerVaults version 4.2.5
[05:05:17 INFO]: Website: https://www.spigotmc.org/resources/51204/
[05:05:17 INFO]: Authors: drtshock, kashike and CmdrKittens

> version factions
[05:05:41 INFO]: Factions version 1.6.9.5-U0.6.9-b281
[05:05:41 INFO]: Website: https://www.spigotmc.org/resources/factionsuuid.1035/
[05:05:41 INFO]: Authors: Olof Larsson, Brett Flannigan, drtshock, dariasc, CmdrKittens and mbaxter

And a raw /f vault no longer gets a stacktrace, it now gets a list of vaults.

Thanks!
