### ISSUE TITLE
The enchantment HellForged not working with Factions UUID

### ISSUE THREAD

**Issue by juliusg034** [drtshock/Factions#1465]
Before adding the Factions UUID plugin CrazyEnchantments were working perfectly fine, specifically the enchantment HellForged (repairs items when walking). After adding factions UUID plugin an error occurs in the console and the enchantment HellForge no longer works. Then removing the plugin allows for the enchantment to work again. I am confused because it says that factions UUID is supported in the documentation.

Furthermore changing the version I am using 2.2.8 to the older 2.1.2 fixes the issues with hellForged

Error:
[19:00:50] [Thread-11/WARN]: Exception in thread "Thread-11" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.badbones69.crazyenchantments.paper.api.enums.pdc.Enchant.getLevel(String)" is null
[19:00:50] [Thread-11/WARN]:    at CrazyEnchantments-2.2.8.jar//com.badbones69.crazyenchantments.paper.controllers.settings.EnchantmentBookSettings.getLevel(EnchantmentBookSettings.java:309)
[19:00:50] [Thread-11/WARN]:    at CrazyEnchantments-2.2.8.jar//com.badbones69.crazyenchantments.paper.api.CrazyManager.getLevel(CrazyManager.java:763)
[19:00:50] [Thread-11/WARN]:    at CrazyEnchantments-2.2.8.jar//com.badbones69.crazyenchantments.paper.tasks.processors.ArmorMoveProcessor.process(ArmorMoveProcessor.java:88)
[19:00:50] [Thread-11/WARN]:    at CrazyEnchantments-2.2.8.jar//com.badbones69.crazyenchantments.paper.tasks.processors.ArmorMoveProcessor.process(ArmorMoveProcessor.java:27)
[19:00:50] [Thread-11/WARN]:    at CrazyEnchantments-2.2.8.jar//com.badbones69.crazyenchantments.paper.tasks.processors.Processor.lambda$new$0(Processor.java:17)
[19:00:50] [Thread-11/WARN]:    at java.base/java.lang.Thread.run(Thread.java:840)

### Debug info
*Run `/f ticketinfo` and paste the URL here.*

### Logs
*Give use your logs by going to `logs/latest.log`.*

### Details
*Please explain the problem.*

**Comment by mbax** [comment]
This feels coincidental. Hop over to the support discord and we can try to diagnose this more, regardless of how coincidental it is.
