### ISSUE TITLE
Error /f show

### ISSUE THREAD

**Issue by LooToS** [drtshock/Factions#190]
[16:56:08] [Server thread/INFO]: zLooToS_ issued server command: /f show
[16:56:08] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.12
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-8dc4297-a7287cb]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-8dc4297-a7287cb]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:642) ~[spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1083) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:918) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_25]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-8dc4297-a7287cb]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
    at java.lang.String.replace(Unknown Source) ~[?:1.8.0_25]
    at com.massivecraft.factions.zcore.MCommand.replaceFPlayerTags(MCommand.java:299) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.getToolTips(MCommand.java:280) ~[?:?]
    at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:136) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:129) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:115) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:50) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:133) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:291) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:254) ~[?:?]
    at com.massivecraft.factions.P.handleCommand(P.java:186) ~[?:?]
    at com.massivecraft.factions.P.onCommand(P.java:198) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-8dc4297-a7287cb]
    ... 14 more

**Comment by drtshock** [comment]
Please update.
