### ISSUE TITLE
Strange Error. Seeking Help!

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#331]
Why do I receive this error ? The people can not invite invite player in the faction. How can I fix ?

[20:36:16 INFO]: superdanielll issued server command: /f invite Luke4401

org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.14
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-fcb68de-1e56438]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-fcb68de-1e56438]
        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:714) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:655) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:558) [spigot.jar:git-Spigot-fcb68de-1e56438]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.NullPointerException
        at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:573) ~[?:?]
        at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:552) ~[?:?]
        at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:540) ~[?:?]
        at com.massivecraft.factions.cmd.CmdInvite.perform(CmdInvite.java:55) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:49) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:49) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:290) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:253) ~[?:?]
        at com.massivecraft.factions.P.handleCommand(P.java:163) ~[?:?]
        at com.massivecraft.factions.P.onCommand(P.java:175) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-fcb68de-1e56438]
        ... 15 more

Thank you for your help.

**Comment by ghost** [comment]
FactionsUUID version: v1.6.9.5-U0.1.14
Spigot version: git-Spigot-fcb68de-1e56438 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT )

**Comment by drtshock** [comment]
You need to update to a snapshot on the CI. That version doesn't work on 1.8.3
