### ISSUE TITLE
/f invite an internal error occurred with blah blah

### ISSUE THREAD

**Issue by TheMexicanChip** [drtshock/Factions#338]
I cant do /f invite It says its a internal error?

**Comment by TheMexicanChip** [comment]
[17:40:41] [Server thread/INFO]: TheMexicanChip issued server command: /f invite iTzMJ07
[17:40:41] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.14
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-61ef214]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-61ef214]
at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1077) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:937) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-61ef214]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_03]
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [?:1.7.0_03]
at java.util.concurrent.FutureTask.run(FutureTask.java:166) [?:1.7.0_03]
at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:670) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626) [craftbukkit.jar:git-Bukkit-61ef214]
at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534) [craftbukkit.jar:git-Bukkit-61ef214]
at java.lang.Thread.run(Thread.java:722) [?:1.7.0_03]
Caused by: java.lang.NullPointerException
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:573) ~[?:?]
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:552) ~[?:?]
at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:540) ~[?:?]
at com.massivecraft.factions.cmd.CmdInvite.perform(CmdInvite.java:55) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:49) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:49) ~[?:?]
at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:290) ~[?:?]
at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:253) ~[?:?]
at com.massivecraft.factions.P.handleCommand(P.java:163) ~[?:?]
at com.massivecraft.factions.P.onCommand(P.java:175) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-61ef214]
... 16 more
[17:40:43] [Netty Epoll Server IO #7/INFO]: **Nebula <[Mod]SSJGOD> i have my own base
[17:40:46] [Server thread/INFO]: General_Cookie lost connection: Disconnected
My Console

**Comment by Kakifrucht** [comment]
Update to latest version on jenkins. It actually does invite the player, it just also prints the stacktrace.

**Comment by TheMexicanChip** [comment]
No I bought this factions I hate the new one

**Comment by Kakifrucht** [comment]
Yes, you need to get access to the jenkins build server and then download the latest version. The on on SpigotMC is not compatible with 1.8.3.

Ask drtshock for access.

**Comment by TheMexicanChip** [comment]
Do i put it in my plugins folder

**Comment by TheMexicanChip** [comment]
Wait what all Do i need to do Im so confused all i need to do is have /f invite???

**Comment by drtshock** [comment]
register on https://ci.drtshock.net, tell me your username, and I'll give you access.

**Comment by TheMexicanChip** [comment]
I registerd and my User name is TheMexicanChip

**Comment by mufincookies** [comment]
I registered as well my name is ShmittyJones

**Comment by TheMexicanChip** [comment]
I cant find where to download factions???
