### ISSUE TITLE
Error message upon speaking

### ISSUE THREAD

**Issue by YepImRobbie** [drtshock/Factions#402]
Hi drtshock,

Absolute love your Factions UUID plugin, keep up the good work

I have a bug to report, whenever someone speaks this is out-put in the console:

[01:34:16 ERROR]: Could not pass event AsyncPlayerChatEvent to Factions v1.6.9.5-U0.1.17-b267
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1057) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:995) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1955) ~[?:1.8.0_45]
    at com.massivecraft.factions.listeners.FactionsChatListener.onPlayerChat(FactionsChatListener.java:131) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
    ... 11 more

**Comment by Kakifrucht** [comment]
Seems like your Factions tag settings are wrong. I would suggest to regenerate them. Which Chat plugin are you using?

**Comment by YepImRobbie** [comment]
"Which Chat plugin are you using?" PEX and ChatManager

"...tag settings are wrong. I would suggest to regenerate..." In what file are the faction tags in?

**Comment by Kakifrucht** [comment]
In the conf.json, the settings starting with chatTag.
You can also add the placeholder [FACTION] to your chat plugin template, which is what I would recommend.

**Comment by YepImRobbie** [comment]
Hi,

I deleted the conf.json and let the server reboot.

I still get the following message:

[03:45:40 ERROR]: Could not pass event AsyncPlayerChatEvent to Factions v1.6.9.5-U0.1.17-b267
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1057) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:995) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-6a6b839-b0e81a4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1955) ~[?:1.8.0_45]
    at com.massivecraft.factions.listeners.FactionsChatListener.onPlayerChat(FactionsChatListener.java:131) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6a6b839-b0e81a4]
    ... 11 more

**Comment by Kakifrucht** [comment]
Try disabling the chat tag with /f conf chatTagEnabled false
I don't know the chat plugin you are using, it might be causing the problems.

**Comment by YepImRobbie** [comment]
Awesome!

That did it, although it was /f _config_ chatTagEnabled false

But yeah, thanks dude. :+1:

**Comment by YepImRobbie** [comment]
Uh... what is &7 or light grey in the language files weird <x> language?

**Comment by drtshock** [comment]
If you have a separate issue, make a separate ticket :)
