### ISSUE TITLE
NullPointerException on warp command

### ISSUE THREAD

**Issue by vemacs** [drtshock/Factions#415]
```
[09:55:07] [Server thread/WARN]: [Factions] Task #24121 for Factions v1.6.9.5-U0.1.17-b42 generated an exception
java.lang.NullPointerException
        at com.massivecraft.factions.cmd.CmdFWarp$1.run(CmdFWarp.java:49) ~[?:?]
        at com.massivecraft.factions.util.WarmUpUtil$1.run(WarmUpUtil.java:28) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-PaperSpigot-07ff818-0a645a2]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:772) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:372) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:703) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:606) [spigot.jar:git-PaperSpigot-07ff818-0a645a2]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

b42 is from my own CI, it's equivalent to e7f80604417da231edbe646ec1610d37d7294999

**Comment by drtshock** [comment]
Shouldn't happen anymore.
