### ISSUE TITLE
Please allow us to do /f show from the console

### ISSUE THREAD

**Issue by roastnewt** [drtshock/Factions#455]
Doing /f show <faction> in server console throws an exception.  I think it expects a player.  Every once in a while, when I'm working on something in console rather than in-game, I'd like to be able to see which faction someone is in, etc., so it would be nice if you could add this feature.

Stack trace follows.

```
[12:46:52] [Server thread/ERROR]: Could not pass event ServerCommandEvent to Factions v1.6.9.5-U0.1.17-b274
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:340) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:308) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-b7d1dd8]
Caused by: java.lang.NullPointerException
    at java.lang.String.replace(String.java:2228) ~[?:1.8.0_45]
    at com.massivecraft.factions.zcore.util.TagReplacer.replace(TagReplacer.java:244) ~[?:?]
    at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:71) ~[?:?]
    at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:80) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
    at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:313) ~[?:?]
    at com.massivecraft.factions.zcore.MPluginSecretServerListener.onServerCommand(MPluginSecretServerListener.java:22) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor605.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    ... 8 more
[12:46:52] [Server thread/WARN]: Unexpected exception while parsing console command "f who kkk"
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.17-b274
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:752) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.DedicatedServer.aB(DedicatedServer.java:344) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:308) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-PaperSpigot-b7d1dd8]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-b7d1dd8]
Caused by: java.lang.NullPointerException
    at java.lang.String.replace(String.java:2228) ~[?:1.8.0_45]
    at com.massivecraft.factions.zcore.util.TagReplacer.replace(TagReplacer.java:244) ~[?:?]
    at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:71) ~[?:?]
    at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:80) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:302) ~[?:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:265) ~[?:?]
    at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
    at com.massivecraft.factions.P.onCommand(P.java:192) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-PaperSpigot-b7d1dd8]
    ... 8 more
```

**Comment by Agazed** [comment]
Update to the latest build.

**Comment by drtshock** [comment]
^ was fixed.
