### ISSUE TITLE
Factions issue

### ISSUE THREAD

**Issue by OregonNelson** [drtshock/Factions#459]
I've gotten this issue when starting up my server, it is up to date though.

[10:16:15] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.1.15-SNAPSHOT
[10:16:15] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.15-SNAPSHOT] === ENABLE START ===
[10:16:15] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.1.15-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
    at com.massivecraft.factions.zcore.persist.json.JSONFPlayers.loadCore(JSONFPlayers.java:91) ~[?:?]
    at com.massivecraft.factions.zcore.persist.json.JSONFPlayers.load(JSONFPlayers.java:68) ~[?:?]
    at com.massivecraft.factions.P.onEnable(P.java:74) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-081dfa5-ba8f630]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:355) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:315) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-081dfa5-ba8f630]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

**Comment by Kakifrucht** [comment]
Why would you think that you are up to date? Current version is U0.1.17

**Comment by drtshock** [comment]
Update + your file is probably corrupt
