### ISSUE TITLE
/f show error

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#647]
Whenever I attempt to run the command /f show, it gives me an error, I attempted to reset the config and this is the error I got with the default config

Edit: After removing  

```
  - '<a>Allies(<i>{allies}<a>/<i>{max-allies}<a>): {allies-list} '
  - '<a>Online: (<i>{online}<a>/<i>{members}<a>): {online-list}'
  - '<a>Offline: (<i>{offline}<a>/<i>{members}<a>): {offline-list}'
```

from my config, I get no error.

Another Edit: I found that just removing all the lists fixes the error, so it's something to do with the player/factions list

```
16:33:49 INFO]: Matt80000 issued server command: /f create Test
[16:33:49 INFO]: [Factions v${project.version}] Matt80000 created a new faction:
 Test
[16:33:54 INFO]: Matt80000 issued server command: /f show
[16:33:54 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' i
n plugin Factions v${project.version}
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[pat
ched.jar:git-PaperSpigot-a187a0f-unknown]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
2) ~[patched.jar:git-PaperSpigot-a187a0f-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServe
r.java:665) ~[patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerCon
nection.java:1189) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:1001) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:45) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java
:1) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_51]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.ja
r:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
73) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
78) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:7
13) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:616) [patched.jar:git-PaperSpigot-a187a0f-unknown]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: mkremins/fanciful/FancyMessage
        at com.massivecraft.factions.zcore.util.TextUtil.toFancy(TextUtil.java:6
7) ~[?:?]
        at com.massivecraft.factions.zcore.util.TextUtil.parseFancy(TextUtil.jav
a:62) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:13
2) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:
95) ~[?:?]
        at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:85) ~[?:?]

        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~
[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:
?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~
[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:
?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~
[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:29
9) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:26
2) ~[?:?]
        at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
        at com.massivecraft.factions.P.onCommand(P.java:191) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[pat
ched.jar:git-PaperSpigot-a187a0f-unknown]
        ... 15 more
>
```

```
```

**Comment by juIio** [comment]
Change 

```
<a>Allies(<i>{allies}<a>/<i>{max-allies}<a>): {allies-list} '
```

To

```
<a>Allies: (<i>{allies}<a>/<i>{max-allies}<a>): {allies-list} '
```

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
