### ISSUE TITLE
Error when running factions

### ISSUE THREAD

**Issue by Piggles** [drtshock/Factions#66]
I receive an error with factions when it attempts to enable. here is my server log

[17:50:33] [Server thread/INFO]: Starting minecraft server version 1.7.10
[17:50:33] [Server thread/INFO]: Loading properties
[17:50:33] [Server thread/INFO]: Default game type: SURVIVAL
[17:50:33] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-205-g3633afe (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[17:50:33] [Server thread/INFO]: Debug logging is disabled
[17:50:33] [Server thread/INFO]: Using 4 threads for Netty based IO
[17:50:33] [Server thread/INFO]: Server Ping Player Sample Count: 12
[17:50:33] [Server thread/INFO]: Generating keypair
[17:50:33] [Server thread/INFO]: Starting Minecraft server on _:25568
[17:50:34] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[17:50:34] [Server thread/INFO]: [Carbon] Loading Carbon v1.6.3
[17:50:35] [Server thread/INFO]: Carbon has finished injecting all 1.8 functionalities.
[17:50:35] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v5.6.2
[17:50:35] [Server thread/INFO]: [Essentials] Loading Essentials v2.13.1
[17:50:35] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.13.1
[17:50:35] [Server thread/INFO]: [Factions] Loading Factions v1.6.9.5-U0.1.5
[17:50:35] [Server thread/INFO]: *_*\* Beginning UUID conversion, this may take A LONG time ****
[17:50:35] [Server thread/INFO]: Preparing level "world"
[17:50:35] [Server thread/INFO]: -------- World Settings For [world] --------
[17:50:35] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:50:35] [Server thread/INFO]: View Distance: 10
[17:50:35] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:50:35] [Server thread/INFO]: Clear tick list: false
[17:50:35] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:50:35] [Server thread/INFO]: Item Merge Radius: 2.5
[17:50:35] [Server thread/INFO]: Item Despawn Rate: 6000
[17:50:35] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:50:35] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:50:35] [Server thread/INFO]: Mob Spawn Range: 4
[17:50:35] [Server thread/INFO]: Anti X-Ray: true
[17:50:35] [Server thread/INFO]:    Engine Mode: 1
[17:50:35] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:50:35] [Server thread/INFO]:    Replace Blocks: [1, 5]
[17:50:35] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:50:35] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:50:35] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:50:35] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:50:35] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:50:35] [Server thread/INFO]: Random Lighting Updates: false
[17:50:35] [Server thread/INFO]: Structure Info Saving: true
[17:50:35] [Server thread/INFO]: Sending up to 5 chunks per packet
[17:50:35] [Server thread/INFO]: Max Entity Collisions: 8
[17:50:35] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:50:35] [Server thread/INFO]: Max TNT Explosions: 100
[17:50:35] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[17:50:35] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:50:35] [Server thread/INFO]: View Distance: 10
[17:50:35] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:50:35] [Server thread/INFO]: Clear tick list: false
[17:50:35] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:50:35] [Server thread/INFO]: Item Merge Radius: 2.5
[17:50:35] [Server thread/INFO]: Item Despawn Rate: 6000
[17:50:35] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:50:35] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:50:35] [Server thread/INFO]: Mob Spawn Range: 4
[17:50:35] [Server thread/INFO]: Anti X-Ray: true
[17:50:35] [Server thread/INFO]:    Engine Mode: 1
[17:50:35] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:50:35] [Server thread/INFO]:    Replace Blocks: [1, 5]
[17:50:35] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:50:35] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:50:35] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:50:35] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:50:35] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:50:35] [Server thread/INFO]: Random Lighting Updates: false
[17:50:35] [Server thread/INFO]: Structure Info Saving: true
[17:50:35] [Server thread/INFO]: Sending up to 5 chunks per packet
[17:50:35] [Server thread/INFO]: Max Entity Collisions: 8
[17:50:35] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:50:35] [Server thread/INFO]: Max TNT Explosions: 100
[17:50:35] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[17:50:35] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[17:50:35] [Server thread/INFO]: View Distance: 10
[17:50:35] [Server thread/INFO]: Chunks to Grow per Tick: 650
[17:50:35] [Server thread/INFO]: Clear tick list: false
[17:50:35] [Server thread/INFO]: Experience Merge Radius: 3.0
[17:50:35] [Server thread/INFO]: Item Merge Radius: 2.5
[17:50:35] [Server thread/INFO]: Item Despawn Rate: 6000
[17:50:35] [Server thread/INFO]: Arrow Despawn Rate: 1200
[17:50:35] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[17:50:35] [Server thread/INFO]: Mob Spawn Range: 4
[17:50:35] [Server thread/INFO]: Anti X-Ray: true
[17:50:35] [Server thread/INFO]:    Engine Mode: 1
[17:50:35] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:50:35] [Server thread/INFO]:    Replace Blocks: [1, 5]
[17:50:35] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[17:50:35] [Server thread/INFO]: Cactus Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Cane Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Melon Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Sapling Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Wheat Growth Modifier: 100%
[17:50:35] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[17:50:35] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:50:35] [Server thread/INFO]: Alternative Hopper Ticking: false
[17:50:35] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[17:50:35] [Server thread/INFO]: Random Lighting Updates: false
[17:50:35] [Server thread/INFO]: Structure Info Saving: true
[17:50:35] [Server thread/INFO]: Sending up to 5 chunks per packet
[17:50:35] [Server thread/INFO]: Max Entity Collisions: 8
[17:50:35] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:50:35] [Server thread/INFO]: Max TNT Explosions: 100
[17:50:35] [Server thread/INFO]: Preparing start region for level 0 (Seed: 8885041066091660163)
[17:50:36] [Server thread/INFO]: Preparing spawn area: 42%
[17:50:37] [Server thread/INFO]: Preparing spawn area: 94%
[17:50:37] [Server thread/INFO]: Preparing start region for level 1 (Seed: -558293822394463348)
[17:50:38] [Server thread/INFO]: Preparing spawn area: 61%
[17:50:39] [Server thread/INFO]: Preparing start region for level 2 (Seed: -558293822394463348)
[17:50:39] [Server thread/INFO]: [Carbon] Enabling Carbon v1.6.3
[17:50:39] [Server thread/INFO]: ProtocolLib not found, not hooking. 1.7 clients not supported.
[17:50:39] [Server thread/INFO]: Carbon is enabled.
[17:50:39] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v5.6.2
[17:50:39] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[17:50:39] [Server thread/INFO]: [Essentials] Enabling Essentials v2.13.1
[17:50:39] [Server thread/INFO]: Bukkit version format changed. Version not checked.
[17:50:39] [Server thread/INFO]: git-Spigot-1.7.9-R0.2-205-g3633afe (MC: 1.7.10)
[17:50:39] [Server thread/INFO]: 1.7.10-R0.1-SNAPSHOT
[17:50:39] [Server thread/INFO]: Essentials: Using config file enhanced permissions.
[17:50:39] [Server thread/INFO]: Permissions listed in as player-commands will be given to all users.
[17:50:39] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.13.1
[17:50:39] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.1.5
[17:50:39] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.5] === ENABLE START ===
[17:50:39] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.1.5 (Is it up to date?)
java.lang.AssertionError
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:686) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.TypeAdapters$24.create(TypeAdapters.java:715) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.getAdapter(Gson.java:353) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.getAdapter(Gson.java:353) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:82) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:81) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:118) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:72) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.getAdapter(Gson.java:353) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:754) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:721) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:670) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.libs.com.google.gson.Gson.fromJson(Gson.java:642) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at com.massivecraft.factions.zcore.util.Persist.load(Persist.java:123) ~[?:?]
    at com.massivecraft.factions.zcore.util.Persist.loadOrSaveDefault(Persist.java:73) ~[?:?]
    at com.massivecraft.factions.zcore.util.Persist.loadOrSaveDefault(Persist.java:63) ~[?:?]
    at com.massivecraft.factions.Conf.load(Conf.java:352) ~[?:?]
    at com.massivecraft.factions.P.onEnable(P.java:90) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:360) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:334) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:290) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:210) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [patch.jar:git-Spigot-1.7.9-R0.2-205-g3633afe]
[17:50:40] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:50:40] [Server thread/INFO]: Done (5.158s)! For help, type "help" or "?"
[17:50:40] [Server thread/INFO]: [Carbon] Editing world: world
[17:50:40] [Server thread/INFO]: [Carbon] Adding populator for world: world
[17:50:40] [Server thread/INFO]: [Carbon] Done editing world: world

**Comment by drtshock** [comment]
You likely touched one of your factions conf files and it messed it up. Run it through a json parser.
