### ISSUE TITLE
InvalidPlugin exception

### ISSUE THREAD

**Issue by rrdvos** [drtshock/Factions#676]
`[14:20:00 ERROR]: Could not load 'plugins/RogueTags.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:293) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:767) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.Bukkit.reload(Bukkit.java:556) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_77]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_77]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    ... 14 more
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.iface.RelationParticipator
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_77]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_77]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_77]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_77]
    at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_77]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot_server.jar:git-PaperSpigot-"ee63dbe"]
    ... 14 more
`

This is the error I get when I'm trying to launch my plugin. It depends on factions, iTag and Protocollib.
This is the plugins code btw:

`    @Override
    public void onEnable() {
        super.onEnable();
        this.getLogger().info("RogueTags by TheRandomGamer has been enabled");
        this.getServer().getPluginManager().registerEvents(this,this);
    }
    @EventHandler(priority = EventPriority.HIGH)
    public void onNameTagReceive(AsyncPlayerReceiveNameTagEvent e){
        Player r = e.getPlayer();
        Player p = e.getNamedPlayer();
        FPlayer fr = FPlayers.getInstance().getByPlayer(r);
        FPlayer pr = FPlayers.getInstance().getByPlayer(p);
        String oldTag = e.getTag();
        if(fr.getRelationTo(pr) == Relation.MEMBER){
            e.setTag(ChatColor.GREEN+oldTag);
        }else if(fr.getRelationTo(pr) == Relation.ALLY){
            e.setTag(ChatColor.LIGHT_PURPLE+oldTag);
        }else if(fr.getRelationTo(pr) == Relation.ENEMY){
            e.setTag(ChatColor.RED+oldTag);
        }
    }

```
     @EventHandler
public void onMemberShipChange(FactionPlayerEvent e){
    Player p = e.getfPlayer().getPlayer();
    TagAPI.refreshPlayer(p);
```

   }

}`

**Comment by drtshock** [comment]
Obviously this is for the wrong factions version.
