### ISSUE TITLE
Random Error I can't understand.

### ISSUE THREAD

**Issue by whuppydog** [drtshock/Factions#744]
ava.lang.NumberFormatException: For input string: "R"
    at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_92]
    at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_92]
    at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.createChatPacket(FancyMessage.java:644) ~[Factions.jar:?]
    at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:617) [Factions.jar:?]
    at com.massivecraft.factions.shade.mkremins.fanciful.FancyMessage.send(FancyMessage.java:605) [Factions.jar:?]
    at com.massivecraft.factions.cmd.CmdInvite.perform(CmdInvite.java:55) [Factions.jar:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) [Factions.jar:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) [Factions.jar:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) [Factions.jar:?]
    at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) [Factions.jar:?]
    at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) [Factions.jar:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299) [Factions.jar:?]
    at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262) [Factions.jar:?]
    at com.massivecraft.factions.P.handleCommand(P.java:189) [Factions.jar:?]
    at com.massivecraft.factions.P.onCommand(P.java:200) [Factions.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-6016ac7-10c10b3]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-6016ac7-10c10b3]
    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-6016ac7-10c10b3]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
    at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [server.jar:git-Spigot-6016ac7-10c10b3]
    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [server.jar:git-Spigot-6016ac7-10c10b3]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
