### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheTechnologyStudio** [drtshock/Factions#789]
[12:46:28 INFO]: MemorexOG issued server command: /f leave

org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.19-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendFlatfile.accountExists(EconomyStorageBackendFlatfile.java:75) ~[?:?]
        at org.appledash.saneeconomy.economy.EconomyManager.accountExists(EconomyManager.java:51) ~[?:?]
        at org.appledash.saneeconomy.vault.EconomySaneEconomy.hasAccount(EconomySaneEconomy.java:54) ~[?:?]
        at com.massivecraft.factions.integration.Econ.hasAccount(Econ.java:383) ~[?:?]
        at com.massivecraft.factions.zcore.persist.MemoryFaction.getAccountId(MemoryFaction.java:236) ~[?:?]
        at com.massivecraft.factions.zcore.persist.MemoryFPlayer.leave(MemoryFPlayer.java:647) ~[?:?]
        at com.massivecraft.factions.cmd.CmdLeave.perform(CmdLeave.java:26) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:130) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:116) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:53) ~[?:?]
        at com.massivecraft.factions.zcore.MCommand.execute(MCommand.java:134) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:299) ~[?:?]
        at com.massivecraft.factions.zcore.MPlugin.handleCommand(MPlugin.java:262) ~[?:?]
        at com.massivecraft.factions.P.handleCommand(P.java:180) ~[?:?]
        at com.massivecraft.factions.P.onCommand(P.java:191) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-798f32d-0cd0397]
        ... 15 more

**Comment by drtshock** [comment]
Your economy plugin is broken / returning null when it shouldn't.
