### ISSUE TITLE
I don't know what to title this.

### ISSUE THREAD

**Issue by ghost** [drtshock/Factions#868]
I noticed players shooting each other in a warzone with flame bows. This error message spammed my console. I can't figure out what is wrong.
[21:57:47] [Server thread/ERROR]: Could not pass event EntityCombustByEntityEvent to Factions v1.6.9.5-U0.1.19-RC2org.bukkit.event.EventExceptionat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.EntityArrow.a(EntityArrow.java:279) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.EntityArrow.A_(EntityArrow.java:194) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.EntityTippedArrow.A_(EntityTippedArrow.java:72) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1652) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.World.g(World.java:1627) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1453) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:635) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:806) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDamageByEntityEvent.(Lorg/bukkit/entity/Entity;Lorg/bukkit/entity/Entity;Lorg/bukkit/event/entity/EntityDamageEvent$DamageCause;I)Vat com.massivecraft.factions.listeners.FactionsEntityListener.onEntityCombustByEntity(FactionsEntityListener.java:201) ~[?:?]at sun.reflect.GeneratedMethodAccessor535.invoke(Unknown Source) ~[?:?]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-4d99fed]... 15 more

**Comment by ghost** [comment]
It seems to have stopped. Still something to look into I guess.

**Comment by Kakifrucht** [comment]
Very weird issue, apparently it is interpreting the 0 in the source as Integer, randomly?
Adding a d behind it fixed the issue for me, however it didn't happen on my other system to start with.

**Comment by Kakifrucht** [comment]
Pull request: #870

**Comment by ghost** [comment]
Add a d behind what?

**Comment by Kakifrucht** [comment]
I mean in the code declaring it as a double.

**Comment by ghost** [comment]
Oh ok.

**Comment by ghost** [comment]
I'm getting this error message constantly now.
