### ISSUE TITLE
issue on 1.11.2

### ISSUE THREAD

**Issue by PhanaticD** [drtshock/Factions#883]
```
[05:38:28 ERROR]: Could not pass event EntityCombustByEntityEvent to Factions v1.6.9.5-U0.1.19-RC2
java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDamageByEntityEvent.<init>(Lorg/bukkit/entity/Entity;Lorg/bukkit/entity/Entity;Lorg/bukkit/event/entity/EntityDamageEvent$DamageCause;I)V
        at com.massivecraft.factions.listeners.FactionsEntityListener.onEntityCombustByEntity(FactionsEntityListener.java:201) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor782.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.2.jar:git-Paper-1009]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.2.jar:git-Paper-1009]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.2.jar:git-Paper-1009]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.2.jar:git-Paper-1009]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.EntityHuman.attack(EntityHuman.java:1017) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.EntityPlayer.attack(EntityPlayer.java:1199) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1607) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.11.2.jar:git-Paper-1009]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:821) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.2.jar:git-Paper-1009]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.2.jar:git-Paper-1009]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by drtshock** [comment]
Nice of them to remove that.. Need to recompile.

**Comment by Kakifrucht** [comment]
#868, I had already fixed this in #870

**Comment by PhanaticD** [comment]
@Kakifrucht how did you manage to compile I always get https://github.com/drtshock/Factions/issues/882

**Comment by Mineacer** [comment]
I get this error too, no idea how to fix this.

**Comment by Kakifrucht** [comment]
I may have still had the repos in my local cache.

**Comment by drtshock** [comment]
Fixed by @Kakifrucht <3
