### ISSUE TITLE
GroupManager issue (Please support this!)

### ISSUE THREAD

**Issue by Sean040299** [drtshock/Factions#892]
```
``14.01 15:54:02 [Server] INFO Gui_ issued server command: /f show lgang
14.01 15:54:02 [Server] ERROR null
14.01 15:54:02 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.1.20
14.01 15:54:02 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
14.01 15:54:02 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [Paperspigot:git-PaperSpigot-"8b18730"]
14.01 15:54:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
14.01 15:54:02 [Server] INFO Caused by: java.lang.NullPointerException
14.01 15:54:02 [Server] INFO at org.anjocaido.groupmanager.dataholder.OverloadedWorldHolder.getUser(OverloadedWorldHolder.java:47) ~[?:?]
14.01 15:54:02 [Server] INFO at org.anjocaido.groupmanager.permissions.AnjoPermissionsHandler.getGroup(AnjoPermissionsHandler.java:94) ~[?:?]
14.01 15:54:02 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:332) ~[?:?]
14.01 15:54:02 [Server] INFO at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
14.01 15:54:02 [Server] INFO at com.massivecraft.factions.P.getPrimaryGroup(P.java:329) ~[?:?]
14.01 15:54:02 [Server] INFO at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:153) ~[?:?]
14.01 15:54:02 [Server] INFO at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:49) ~[?:?]
14.01 15:54:02 [Server] INFO at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:232) ~[?:?]
14.01 15:54:02 [Server] INFO at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:193) ~[?:?]
14.01 15:54:02 [Server] INFO at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:95) ~[?:?]
14.01 15:54:05 [Multicraft] Skipped 12 lines due to rate limit (30/s)``
```

**Comment by Kakifrucht** [comment]
GroupManager is outdated and shouldn't be used anymore.
Many alternatives out there. I personally prefer bPermissions.

**Comment by Sean040299** [comment]
What does it support? Is there a list?

**Comment by Sean040299** [comment]
Maybe add support for groupManagerX? As that is a thing now

**Comment by Kakifrucht** [comment]
It was abandoned and is not a very clean plugin to start with. The bug you are having is completely your plugins fault.

**Comment by Sean040299** [comment]
GroupManagerX is new.. Not abandoned LOL

**Comment by Kakifrucht** [comment]
Look at your stacktrace. Why do you come here asking for support? If you are not using an abandoned plugin, ask the dev to fix it.

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
