### ISSUE TITLE
Factions UUID Not Loading

### ISSUE THREAD

**Issue by Jeruhmii** [drtshock/Factions#915]
Hey,
Randomly, the plugin broke and now won't launch anymore. I'm super confused.

[07:14:22] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.1.20
[07:14:22] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] === ENABLE START ===
[07:14:22] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.1.20 (Is it up to date?)
com.massivecraft.factions.shade.com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 6233 column 3
	at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:889) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:844) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:793) ~[?:?]
	at com.massivecraft.factions.zcore.persist.json.JSONFPlayers.loadCore(JSONFPlayers.java:92) ~[?:?]
	at com.massivecraft.factions.zcore.persist.json.JSONFPlayers.load(JSONFPlayers.java:73) ~[?:?]
	at com.massivecraft.factions.P.onEnable(P.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [Spigot.jar:git-PaperSpigot-"8b18730"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.io.EOFException: End of input at line 6233 column 3
	at com.massivecraft.factions.shade.com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1408) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.stream.JsonReader.doPeek(JsonReader.java:498) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.stream.JsonReader.hasNext(JsonReader.java:418) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[?:?]
	at com.massivecraft.factions.shade.com.google.gson.Gson.fromJson(Gson.java:879) ~[?:?]
	... 16 more
[07:14:22] [Server thread/INFO]: [Factions] Disabling Factions v1.6.9.5-U0.1.20
[07:14:22] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.20] Disabled

**Comment by CmdrKittens** [comment]
This is an issue of data corruption in the players file.
