### ISSUE TITLE
FactionsUUID Not Loading - MassiveCraft Issue [Solved]

### ISSUE THREAD

**Issue by kashalls** [drtshock/Factions#916]
FactionsUUId is not loading due to some kind of issue with MassiveCraft.

> [13:15:10] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.1.19-RC2 (Is it up to date?)
java.lang.NoSuchMethodError: com.massivecraft.factions.Factions.getInstance()Lcom/massivecraft/factions/Factions;
	at com.massivecraft.factions.P.onEnable(P.java:79) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:362) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:322) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

> Massivecraft: [13:14:55] [Server thread/ERROR]: Could not load 'plugins/MassiveCore.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:297) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at com.massivecraft.massivecore.MassivePlugin.<init>(MassivePlugin.java:19) ~[?:?]
	at com.massivecraft.massivecore.MassiveCore.<init>(MassiveCore.java:119) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at me.Max604.BedrockMiner.Main.<init>(Main.java:30) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot10.jar:git-Spigot-1e4dd71-5e5cf84]
	... 6 more

**Comment by kashalls** [comment]
Solved this by replacing the jar with a new one.
