### ISSUE TITLE
MassiveCombat & FactionsUUID issue.

### ISSUE THREAD

**Issue by ChimpGamer** [drtshock/Factions#968]
When I run FactionsUUID MassiveCombat seems to be complaining about an Missing class that has to do with Factions. Is this an issue on MassiveCombat's side or FactionsUUID?

`[22:36:29] [Server thread/INFO]: [MassiveCombat 2.13.0-SNAPSHOT] Integration Activation IntegrationFactions FAILED:
[22:36:29] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/RelationParticipator
[22:36:29] [Server thread/WARN]: 	at com.massivecraft.massivecombat.integration.factions.IntegrationFactions.getEngine(IntegrationFactions.java:26)
[22:36:29] [Server thread/WARN]: 	at com.massivecraft.massivecore.Integration.getEngines(Integration.java:102)
[22:36:29] [Server thread/WARN]: 	at com.massivecraft.massivecore.Integration.setIntegrationActiveEngines(Integration.java:93)
[22:36:29] [Server thread/WARN]: 	at com.massivecraft.massivecore.Integration.setIntegrationActive(Integration.java:67)
[22:36:29] [Server thread/WARN]: 	at com.massivecraft.massivecore.Integration.setIntegrationActive(Integration.java:84)
[22:36:29] [Server thread/WARN]: 	at com.massivecraft.massivecore.Integration.onPluginEnable(Integration.java:181)
[22:36:29] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor162.execute(Unknown Source)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44)
[22:36:29] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:378)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:328)
[22:36:29] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:438)
[22:36:29] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:399)
[22:36:29] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337)
[22:36:29] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:276)
[22:36:29] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:612)
[22:36:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[22:36:29] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator
[22:36:29] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102)
[22:36:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87)
[22:36:29] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:36:29] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:36:29] [Server thread/WARN]: 	... 22 more`

**Comment by markhughes** [comment]
MassiveCombat & FactionsUUID are not compatible. 

MassiveCombat will always attempt to hook into MassiveCraft's Factions v2 because it uses the same name.
