### ISSUE TITLE
I have this error spammed in console

### ISSUE THREAD

**Issue by Bolbec** [drtshock/Factions#973]
```
21.10 02:06:43 [Server] INFO ... 16 more
21.10 02:06:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
21.10 02:06:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
21.10 02:06:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
21.10 02:06:43 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
21.10 02:06:43 [Server] INFO at com.massivecraft.factions.listeners.FactionsEntityListener.onPotionSplashEvent(FactionsEntityListener.java:242) ~[?:?]
21.10 02:06:43 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDamageByEntityEvent.&lt;init&gt;(Lorg/bukkit/entity/Entity;Lorg/bukkit/entity/Entity;Lorg/bukkit/event/entity/EntityDamageEvent$DamageCause;I)V
21.10 02:06:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1437) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.World.h(World.java:1603) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1633) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.EntityProjectile.B_(EntityProjectile.java:167) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPotion.a(EntityPotion.java:100) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPotion.a(EntityPotion.java:158) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:347) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot.jar:git-Spigot-7754231-94b0980]
21.10 02:06:43 [Server] INFO org.bukkit.event.EventException: null
21.10 02:06:43 [Server] ERROR Could not pass event PotionSplashEvent to Factions v1.6.9.5-U0.1.17-b${BUILD_NUMBER}
```

Please help.

**Comment by WizzleBear** [comment]
It's v1.6.9.5-U0.1.17
Try updating it to the latest version

**Comment by CmdrKittens** [comment]
I am closing this issue due to its age with the assumption it is no longer a problem. If you encounter this problem, or a similar problem, please create a new issue for it.
