### ISSUE TITLE
Error trying to load Factions!

### ISSUE THREAD

**Issue by ACrispyCookie** [drtshock/Factions#986]
I'm getting this error when Factions is loading:

[16:07:55] [Server thread/INFO]: [Factions] Enabling Factions v1.6.9.5-U0.1.21
[16:07:55] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.21] === ENABLE START ===
[16:07:55] [Server thread/INFO]: [Factions v1.6.9.5-U0.1.21] Loaded 17 players
[16:07:55] [Server thread/ERROR]: Error occurred while enabling Factions v1.6.9.5-U0.1.21 (Is it up to date?)
java.lang.NullPointerException
at com.massivecraft.factions.zcore.persist.json.JSONFactions.loadCore(JSONFactions.java:93) ~[?:?]
at com.massivecraft.factions.zcore.persist.json.JSONFactions.load(JSONFactions.java:73) ~[?:?]
at com.massivecraft.factions.P.onEnable(P.java:79) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by drtshock** [comment]
Consistently? Or just one time? Can you post your factions.json file? It looks like there might be an error.
