### ISSUE TITLE
[TESTING] another error (build 26) [blockplaceevent]

### ISSUE THREAD

**Issue by SayNada** [drtshock/Factions#997]
I believe this is to do with "/f perm" - also the command /f perm doesn't work on 1.8.8

[15:40:48] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Factions v1.6.9.5-U0.2.0-SNAPSHOT-b26
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader.execute(JavaPluginLoader.java:302) ~[minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:127) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.ItemStack.placeItem(ItemStack.java:160) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:503) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.run(SourceFile:13) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: No enum constant com.massivecraft.factions.zcore.fperms.Action.build
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_151]
	at com.massivecraft.factions.zcore.fperms.Action.valueOf(Action.java:3) ~[Factions.jar:?]
	at com.massivecraft.factions.listeners.FactionsBlockListener.playerCanBuildDestroyBlock(FactionsBlockListener.java:255) ~[Factions.jar:?]
	at com.massivecraft.factions.listeners.FactionsBlockListener.onBlockPlace(FactionsBlockListener.java:39) ~[Factions.jar:?]
	at sun.reflect.GeneratedMethodAccessor522.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader.execute(JavaPluginLoader.java:300) ~[minecraft_server.jar:git-TacoSpigot-"c98afce0"]
	... 19 more

**Comment by SayNada** [comment]
@drtshock

**Comment by drtshock** [comment]
I get notifications for every action on every ticket. You don't need to ping me :)

**Comment by drtshock** [comment]
Should be fixed in latest dev builds.
